import { useLocalSearchParams, router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '@/api';
import { startTeacherBeacon, stopTeacherBeacon } from '@/ble';

export default function TeacherClass(){const{id}=useLocalSearchParams<{id:string}>();const[data,setData]=useState<any>(null);const[session,setSession]=useState<any>(null);const[rows,setRows]=useState<any[]>([]);const[busy,setBusy]=useState(false);
 const load=async()=>{if(!id)return;try{setData((await api.getClass(id)).class);const current=await api.currentAttendance(id);setSession(current.session);setRows(current.attendance)}catch(e){Alert.alert('Error',e instanceof Error?e.message:'Could not load class')}};
 useEffect(()=>{load(); return()=>{stopTeacherBeacon()}},[]); useEffect(()=>{if(!session)return;const timer=setInterval(async()=>{try{const c=await api.currentAttendance(id!);setSession(c.session);setRows(c.attendance)}catch{}} ,2000);return()=>clearInterval(timer)},[session?.id,id]);
 const start=async()=>{try{setBusy(true);const r=await api.startAttendance(id!);try{await startTeacherBeacon(r.bleToken,r.ble)}catch(e){await api.endAttendance(r.session.id).catch(()=>{});throw e}setSession(r.session)}catch(e){Alert.alert('BLE attendance',e instanceof Error?e.message:'Could not start attendance')}finally{setBusy(false)}};
 const end=async()=>{try{if(session) await api.endAttendance(session.id);await stopTeacherBeacon();setSession(null)}catch(e){Alert.alert('Error',e instanceof Error?e.message:'Could not stop session')}};
 if(!data)return <SafeAreaView style={s.container}><Text>Loading…</Text></SafeAreaView>;
 return <SafeAreaView style={s.container}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>{data.name}</Text><Text style={s.muted}>{data.subject||'Class'} · Join code {data.joinCode}</Text><View style={s.row}><Pressable style={s.secondary} onPress={()=>router.push(`/(teacher)/class/${id}/requests`)}><Text>Student requests</Text></Pressable>{session?<Pressable style={s.stop} onPress={end}><Text style={s.stopText}>Stop beacon</Text></Pressable>:<Pressable style={s.primary} onPress={start} disabled={busy}><Text style={s.primaryText}>{busy?'Starting…':'Start attendance'}</Text></Pressable>}</View>{session&&<View style={s.live}><Text style={s.liveTitle}>Attendance live</Text><Text>Students present: {rows.length}</Text><Text style={s.small}>The phone is advertising the active session over BLE.</Text></View>}<Text style={s.section}>Accepted students</Text>{data.memberships.map((m:any)=><View style={s.student} key={m.studentId}><Text style={s.studentName}>{m.student.name}</Text><Text style={s.muted}>{m.student.email}</Text></View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:'#f7f7fb'},content:{padding:20,gap:12},title:{fontSize:32,fontWeight:'800'},muted:{color:'#666'},row:{flexDirection:'row',gap:10,flexWrap:'wrap'},primary:{backgroundColor:'#111',padding:14,borderRadius:14},primaryText:{color:'white',fontWeight:'700'},stop:{backgroundColor:'#fee2e2',padding:14,borderRadius:14},stopText:{color:'#991b1b',fontWeight:'700'},secondary:{backgroundColor:'white',padding:14,borderRadius:14},live:{backgroundColor:'#e9f7ee',padding:18,borderRadius:18,gap:5},liveTitle:{fontSize:19,fontWeight:'800'},small:{color:'#567'},section:{fontSize:20,fontWeight:'800',marginTop:10},student:{backgroundColor:'white',padding:16,borderRadius:16},studentName:{fontWeight:'800',fontSize:16}})
